language: node_js
node_js:
  - "10"
after_success:
  - npm install coveralls codeclimate-test-reporter
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls || true
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter || true
